"""
Munim.ai -- Report Generation Agent
Generates the monthly Munim Report PDF for traders and their CAs.
Uses fpdf2 (pure Python, no GTK/Pango system dependencies needed).
"""

import logging
from datetime import date
from typing import Optional
from fpdf import FPDF

from app.services.supabase_client import (
    get_supabase,
    get_invoices_for_trader,
    get_itc_summary,
    get_all_suppliers_for_trader,
    get_active_supplier_flags,
    upload_file,
)
from app.services import whatsapp

logger = logging.getLogger(__name__)


class MunimPDF(FPDF):
    """Custom PDF class with Munim branding."""

    def header(self):
        self.set_fill_color(15, 52, 96)
        self.rect(0, 0, 210, 18, 'F')
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 4)
        self.cell(0, 10, 'Munim.ai -- GST Compliance Report', align='L')

    def footer(self):
        self.set_y(-12)
        self.set_font('Helvetica', 'I', 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, 'Generated by Munim.ai | Auto-generated -- verify with CA before filing', align='C')

    def section_title(self, title: str):
        self.ln(4)
        self.set_fill_color(240, 245, 255)
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(15, 52, 96)
        self.cell(0, 7, title, fill=True, ln=True)
        self.ln(2)

    def kv_row(self, key: str, value: str, bold_val=False):
        self.set_font('Helvetica', '', 9)
        self.set_text_color(80, 80, 80)
        self.cell(55, 6, key + ':', ln=False)
        self.set_font('Helvetica', 'B' if bold_val else '', 9)
        self.set_text_color(20, 20, 20)
        self.cell(0, 6, str(value), ln=True)

    def summary_box(self, label: str, amount: str, r: int, g: int, b: int):
        x = self.get_x()
        y = self.get_y()
        self.set_fill_color(r, g, b)
        self.rect(x, y, 59, 20, 'F')
        self.set_font('Helvetica', '', 7)
        self.set_text_color(60, 60, 60)
        self.set_xy(x + 2, y + 2)
        self.cell(55, 5, label.upper(), ln=True)
        self.set_font('Helvetica', 'B', 13)
        self.set_text_color(20, 20, 20)
        self.set_x(x + 2)
        self.cell(55, 11, 'Rs. ' + amount, ln=True)
        self.set_xy(x + 61, y)


def _fmt(n) -> str:
    try:
        return f"{float(n):,.0f}"
    except (TypeError, ValueError):
        return "0"


def _get_fix_action(status: str) -> str:
    return {
        "FIXABLE_BLOCKED": "Correct HSN code/rate before filing",
        "AT_RISK": "Confirm supplier has filed GSTR-1",
        "FRAUD_FLAGGED": "Verify invoice authenticity before claiming",
    }.get(status, "Consult CA")


async def generate_munim_report(
    trader_id: str,
    month: Optional[int] = None,
    year: Optional[int] = None,
) -> Optional[str]:
    """
    Generate the monthly Munim Report PDF and upload to Supabase Storage.
    Returns the public URL of the generated PDF.
    """
    now = date.today()
    month = month or now.month
    year = year or now.year

    month_names = [
        "", "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
    ]

    db = get_supabase()

    # Fetch trader info
    trader_resp = db.table("traders").select("*").eq("id", trader_id).execute()
    if not trader_resp.data:
        logger.error(f"Trader {trader_id} not found")
        return None
    trader_data = trader_resp.data[0]

    # Fetch data
    buckets = await get_itc_summary(trader_id)
    invoices = await get_invoices_for_trader(trader_id, month, year)
    supplier_links = await get_all_suppliers_for_trader(trader_id)

    confirmed = buckets.get("confirmed", 0)
    blocked = buckets.get("fixable_blocked", 0)
    at_risk = buckets.get("at_risk", 0)
    missed = buckets.get("missed", 0)
    total_recovery = blocked + at_risk + missed

    # Build issues list
    issues = []
    for inv in invoices:
        status = inv.get("itc_status", "")
        if status in ("FIXABLE_BLOCKED", "AT_RISK", "FRAUD_FLAGGED"):
            amt = inv.get("itc_amount_blocked") or inv.get("itc_amount_eligible") or 0
            issues.append({
                "supplier": (inv.get("supplier_name") or inv.get("gstin_supplier", "Unknown"))[:30],
                "reason": (inv.get("itc_block_reason") or status)[:60],
                "amount": _fmt(amt),
                "fix": _get_fix_action(status),
            })

    issues.sort(key=lambda x: -float(x["amount"].replace(",", "") or 0))

    # --- Build PDF ---
    pdf = MunimPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_top_margin(22)

    # Title block
    pdf.ln(6)
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(15, 52, 96)
    pdf.cell(0, 8, 'Monthly GST Compliance Report', ln=True)

    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, f"{month_names[month]} {year}  |  Generated: {now.isoformat()}", ln=True)
    pdf.ln(3)

    # Trader info
    pdf.kv_row("Trader", trader_data.get("name", "") + " -- " + trader_data.get("business_name", ""))
    pdf.kv_row("GSTIN", trader_data.get("gstin", "Not provided"))
    pdf.ln(4)

    # Summary boxes
    pdf.section_title("1. ITC Summary")
    pdf.summary_box("Confirmed ITC", _fmt(confirmed), 232, 245, 233)
    pdf.summary_box("Blocked (Fixable)", _fmt(blocked), 255, 243, 224)
    pdf.summary_box("At-Risk", _fmt(at_risk), 252, 228, 236)
    pdf.ln(22)
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 6, f"Total Invoices: {len(invoices)}  |  Missed ITC: Rs. {_fmt(missed)}  |  Recovery Possible: Rs. {_fmt(total_recovery)}", ln=True)
    pdf.ln(3)

    # Issues requiring CA action
    pdf.section_title(f"2. Issues Requiring CA Action ({len(issues)} items)")
    if issues:
        # Table header
        pdf.set_fill_color(245, 245, 245)
        pdf.set_font('Helvetica', 'B', 8)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(55, 6, 'Supplier', border=1, fill=True)
        pdf.cell(75, 6, 'Reason', border=1, fill=True)
        pdf.cell(25, 6, 'Impact (Rs.)', border=1, fill=True)
        pdf.cell(0, 6, 'Fix', border=1, fill=True, ln=True)

        for iss in issues[:20]:
            pdf.set_font('Helvetica', '', 7)
            pdf.set_text_color(20, 20, 20)
            pdf.cell(55, 5, iss["supplier"], border=1)
            pdf.cell(75, 5, iss["reason"], border=1)
            pdf.set_font('Helvetica', 'B', 7)
            pdf.set_text_color(200, 50, 50)
            pdf.cell(25, 5, iss["amount"], border=1)
            pdf.set_font('Helvetica', '', 7)
            pdf.set_text_color(50, 100, 50)
            pdf.cell(0, 5, iss["fix"], border=1, ln=True)
    else:
        pdf.set_font('Helvetica', 'I', 9)
        pdf.set_text_color(100, 160, 100)
        pdf.cell(0, 8, 'No issues this month - all ITC confirmed!', ln=True)
    pdf.ln(4)

    # Invoice table
    pdf.section_title(f"3. All Processed Invoices ({len(invoices)} total)")
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(22, 6, 'Date', border=1, fill=True)
    pdf.cell(60, 6, 'Supplier', border=1, fill=True)
    pdf.cell(28, 6, 'Amount (Rs.)', border=1, fill=True)
    pdf.cell(25, 6, 'ITC (Rs.)', border=1, fill=True)
    pdf.cell(0, 6, 'Status', border=1, fill=True, ln=True)

    STATUS_COLORS = {
        "CONFIRMED": (50, 150, 50),
        "FIXABLE_BLOCKED": (200, 120, 0),
        "AT_RISK": (200, 50, 50),
        "FRAUD_FLAGGED": (140, 0, 180),
    }

    for inv in invoices[:40]:
        itc_status = inv.get("itc_status", "")
        itc_amt = inv.get("itc_amount_eligible") or inv.get("itc_amount_blocked") or 0
        supplier = (inv.get("supplier_name") or inv.get("gstin_supplier") or "Unknown")[:35]
        r, g, b = STATUS_COLORS.get(itc_status, (80, 80, 80))

        pdf.set_font('Helvetica', '', 7)
        pdf.set_text_color(20, 20, 20)
        pdf.cell(22, 5, (inv.get("invoice_date") or "")[:10], border=1)
        pdf.cell(60, 5, supplier, border=1)
        pdf.cell(28, 5, _fmt(inv.get("total_amount", 0)), border=1)
        pdf.cell(25, 5, _fmt(itc_amt), border=1)
        pdf.set_text_color(r, g, b)
        pdf.set_font('Helvetica', 'B', 7)
        pdf.cell(0, 5, itc_status or "PENDING", border=1, ln=True)

    if len(invoices) > 40:
        pdf.set_font('Helvetica', 'I', 7)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 5, f"... and {len(invoices) - 40} more invoices not shown", ln=True)
    pdf.ln(4)

    # Supplier health
    pdf.section_title("4. Supplier Health")
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(65, 6, 'Supplier Name', border=1, fill=True)
    pdf.cell(45, 6, 'GSTIN', border=1, fill=True)
    pdf.cell(25, 6, 'Health Score', border=1, fill=True)
    pdf.cell(25, 6, 'Invoices', border=1, fill=True)
    pdf.cell(0, 6, 'Flags', border=1, fill=True, ln=True)

    for link in supplier_links[:20]:
        sup = link.get("suppliers", {})
        if not sup:
            continue
        flags = await get_active_supplier_flags(sup["id"])
        health = sup.get("health_score", 100) or 100
        r, g, b = (50, 150, 50) if health >= 70 else ((200, 120, 0) if health >= 40 else (200, 50, 50))

        pdf.set_font('Helvetica', '', 7)
        pdf.set_text_color(20, 20, 20)
        pdf.cell(65, 5, (sup.get("legal_name", "Unknown"))[:38], border=1)
        pdf.cell(45, 5, sup.get("gstin", ""), border=1)
        pdf.set_text_color(r, g, b)
        pdf.set_font('Helvetica', 'B', 7)
        pdf.cell(25, 5, f"{health}/100", border=1)
        pdf.set_text_color(20, 20, 20)
        pdf.set_font('Helvetica', '', 7)
        pdf.cell(25, 5, str(link.get("total_invoice_count", 0)), border=1)
        flag_text = ", ".join(f["flag_type"] for f in flags[:2]) if flags else "None"
        pdf.cell(0, 5, flag_text[:30], border=1, ln=True)

    # Generate PDF bytes
    try:
        pdf_bytes = bytes(pdf.output())
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        return None

    # Upload to Supabase Storage
    filename = f"munim_report_{trader_id}_{year}_{month:02d}.pdf"
    pdf_url = await upload_file("reports", filename, pdf_bytes, "application/pdf")

    # Store report metadata
    try:
        db.table("munim_reports").upsert({
            "trader_id": trader_id,
            "month": month,
            "year": year,
            "pdf_url": pdf_url,
            "total_invoices_processed": len(invoices),
            "total_itc_confirmed": confirmed,
            "total_itc_blocked": blocked,
            "total_itc_at_risk": at_risk,
            "total_itc_missed": missed,
            "total_issues_count": len(issues),
        }, on_conflict="trader_id,month,year").execute()
    except Exception as e:
        logger.error(f"Failed to store report metadata: {e}")

    logger.info(f"Munim Report generated for trader {trader_id} -- {month_names[month]} {year}")
    return pdf_url


async def send_report_to_trader(trader_id: str, pdf_url: str):
    """Send the Munim Report PDF to trader and CA via WhatsApp."""
    db = get_supabase()
    trader = db.table("traders").select("*").eq("id", trader_id).execute()
    if not trader.data:
        return

    trader_data = trader.data[0]
    phone = trader_data.get("whatsapp_number")
    if not phone:
        return

    # Send to trader
    await whatsapp.send_text_message(
        phone,
        "📋 Aapka monthly Munim Report tayyar hai!\n\n"
        "Isme hai: ITC summary, issues, supplier health, aur CA ke liye filing data.\n"
        "PDF neeche hai 👇"
    )
    await whatsapp.send_document(phone, pdf_url, "Munim Report", "munim_report.pdf")

    # Send to CA if registered
    ca_phone = trader_data.get("ca_whatsapp_number")
    if ca_phone:
        await whatsapp.send_text_message(
            ca_phone,
            f"📋 Munim Report -- {trader_data.get('business_name', 'Client')}\n\n"
            f"Monthly compliance report ready for review."
        )
        await whatsapp.send_document(ca_phone, pdf_url, "Munim Report", "munim_report.pdf")
